[package]
name = "fium-runtime"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "fium"
path = "src/main.rs"

[dependencies]
anyhow = "1"
axum = "0.7"
axum-server = { version = "0.7", features = ["tls-rustls"] }
rcgen = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["io-util", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }
toml = "0.8"
tower-http = { version = "0.6", features = ["compression-full", "fs", "set-header"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "json"] }
uuid = { version = "1", features = ["v4"] }
fium-transport = { path = "../transport" }
clap = { version = "4.5.60", features = ["derive"] }
include_dir = "0.7.4"
notify = "7"
